homework8/homework8/homework8/blog/urls.py
from django.urls import path

from . import views
app_name = 'blog'
urlpatterns = [
    # ex /blog/
    path('', views.IndexView.as_view(), name='index'),
    # ex /blog/1/
    path('<int:pk>/', views.View.as_view(), name='view'),
]

homework8/homework8/homework8/homework8/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

homework8/homework8/homework8/blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title       = models.CharField(max_length=200)
    content     = models.TextField()
    author_name = models.CharField(max_length=200)
    pub_date    = models.DateTimeField('date published')

homework8/homework8/homework8/blog/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.generic import ListView, DetailView
from .models import Post

# Create your views here.

class IndexView(ListView):
    template_name = 'blog/index.html'
    context_object_name = 'posts'

    def get_queryset(self):
        """Return all the blog posts"""
        return Post.objects.order_by('-pub_date')

class View(DetailView):
    model = Post
    template_name = 'blog/view.html'

homework8/homework8/homework8/blog/templates/blog/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>List of all blog posts</title>
    </head>
    <body>
        <h1>
            List of all blog posts
        </h1>

    {% if posts %}
        <ul>
        {% for post in posts %}
            <li>
                <a href="{% url 'blog:view' post.id %}">
                    {{ post.title }} by <i>{{post.author_name}}</i> ({{post.pub_date}})
                </a>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No posts are available.</p>
    {% endif %}
    </body>
</html>

homework8/homework8/homework8/blog/templates/blog/view.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Blog Post</title>
    </head>
    <body>
        <h1>{{ post.title }}</h1>
        <p> <b>Author:</b> <i>{{post.author_name}}</i></p>
        <p> <b>Published</b> ({{post.pub_date}})</p>
        <p> {{post.content}}</p>
    </body>
</html>